security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        token:
            entity:
                class: App\Entity\User\User
                property: token
        username:
            entity:
                class: App\Entity\User\User
                property: username
        user:
            chain:
                providers: [token, username]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            provider: user
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\SessionAuthenticator
                    - App\Security\OAuthAuthenticator
                    - App\Security\CookieAuthenticator
                    - App\Security\TokenAuthenticator
                entry_point: App\Security\SessionAuthenticator
   
    encoders:
        App\Entity\User\User: bcrypt
