snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%/1"
        session:
            type: predis
            alias: session
            dsn: "%env(REDIS_URL)%/2"
    session:
      client: session
