name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

services:
  mysql:
    image: mysql:8.0
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: nfls_test
    ports:
      - 3306

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Run Production Script
      run: sh ./prod.sh
